Footer
Workflow-Team-Parfume/sephora-project pull request #16
Opened 2024-01-31 19:40 UTC by vitod123

Was created footer

2024-01-31 20:02 UTC, WitchLosser approved these changes

2024-01-31 20:12 UTC, Narkobaron15 requested changes
Fix header and overall CSS namings

2024-01-31 20:27 UTC, WitchLosser commented on sephora-frontend/src/compnents/home/homeFooter/homeFooter.tsx
> +            display: "flex",
create footer-box  style and move this to scss

2024-01-31 20:30 UTC, Narkobaron15 commented
Do links instead of buttons with paddings
![зображення](https://github.com/Workflow-Team-Parfume/sephora-project/assets/95102446/e531153a-48e7-4de7-b181-91c338e45aee)

2024-01-31 21:00 UTC, WitchLosser submitted a review, later dismissed

2024-02-07 20:28 UTC, WitchLosser approved these changes

2024-02-07 20:29 UTC, merged